[build]
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[functions.search]
  runtime = "python3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200