services:
  - type: web
    name: zhihu-search-api
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: source /opt/render/project/.env && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ZHIHU_COOKIE
        sync: false
      - key: CHROMIUM_PATH
        sync: false
        # 这个值会在构建时被build.sh更新
        value: "/opt/render/.local-chromium/chrome-linux/chrome"
    # 增加构建时的资源限制
    buildConfig:
      maxRetries: 3
      memory: 1024
    # 运行时的资源配置
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    healthCheckPath: /
    autoDeploy: true 