services:
  - type: web
    name: zhihu-search-api
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: |
      if [ -f /opt/render/project/.env ]; then
        source /opt/render/project/.env
        echo "已加载环境变量，CHROMIUM_PATH=$CHROMIUM_PATH"
      fi
      uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ZHIHU_COOKIE
        sync: false
    # 增加构建时的资源限制
    buildConfig:
      maxRetries: 3
      memory: 1024
    # 运行时的资源配置
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    healthCheckPath: /
    autoDeploy: true 